(fgenv) PS C:\users\vpfeifer\Desktop\FG-speech\egocentric-fg-speech-detection> python foreground.py no_spaces.txt vit-small-f128-t6_DSE.csv
 17%|███████████████▏                                                                        | 106/614 [12:33<1:00:10,  7.11s/it]
Traceback (most recent call last):
  File "foreground.py", line 105, in <module>
    inference(dataloader, audio_model, args.out_file, device)
  File "foreground.py", line 68, in inference
    for audio_file, audio_input in tqdm(dataloader):
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\users\vpfeifer\Desktop\FG-speech\egocentric-fg-speech-detection\foreground.py", line 43, in __getitem__
    waveform = transform(waveform)
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torchaudio\transforms\_transforms.py", line 1002, in forward
    return _apply_sinc_resample_kernel(waveform, self.orig_freq, self.new_freq, self.gcd, self.kernel, self.width)
  File "C:\Users\vpfeifer\Anaconda3\envs\fgenv\lib\site-packages\torchaudio\functional\functional.py", line 1532, in _apply_sinc_resample_kernel
    waveform = waveform.view(-1, shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous